package FORMS;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalUnit;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
/**
 *
 * @author Sistemas1
 */
public class Inicio extends javax.swing.JFrame {
    /**
     * Creates new form Inicio
     */
    
    public Inicio() {
        initComponents();
    }
    
    
    public static String notas (String mensaje) {
        try {
            String hora = hora ();
            File TextFile = new File("c:/bitacora.txt");
            FileWriter TextOut = new FileWriter(TextFile, true);
            TextOut.write("\n"+mensaje+"    -"+hora+"\n");
            TextOut.close();
        }
        catch (Exception notas) {
            System.out.println("ERROR EN GRABACION EN BITACORA: "+notas);
        }
        String grabado = "grabado";
        return (grabado);
    }
    
    public static String hora ( ) {
        Calendar calendar =Calendar.getInstance(); //obtiene la fecha de hoy 
        Calendar calendario = new GregorianCalendar();
        int hora, minutos, segundos;
        hora =calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
        String horas = hora + ":" + minutos + ":" + segundos;
        String fecha = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        String fechas = fecha+"/"+horas;
        return (fechas);
    }
    
    void CrearTabla () {
        Calendar calendar =Calendar.getInstance(); //obtiene la fecha de hoy 
        // viernes
        String viernes = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        // actual
        String actual = viernes;
        System.out.println("Fecha actual "+actual);
        // confirmacion viernes
        System.out.println(viernes);
        String jueves, miercoles, martes, lunes, domingo, sabado; 
        // jueves
        calendar.add(Calendar.DATE, -1);
        jueves = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(jueves);
        // miercoles
        calendar.add(Calendar.DATE, -1);
        miercoles = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(miercoles);
        // martes
        calendar.add(Calendar.DATE, -1);
        martes = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(martes);
        // lunes
        calendar.add(Calendar.DATE, -1);
        lunes = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(lunes);
        // domingo
        calendar.add(Calendar.DATE, -1);
        domingo = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(domingo);
        // sabado
        calendar.add(Calendar.DATE, -1);
        sabado = (String.format("%1$td-%1$tm-%1$ty",  calendar.getTime()));
        System.out.println(sabado);
        //crando tabla
        try {
            ConexionSQL con = new ConexionSQL();
            Connection cn = con.Conectar();
            String sentencia="CREATE TABLE `reporte"+actual+"` ("+ "No VARCHAR(4), " + "Nombre VARCHAR(80), `"+sabado+"` VARCHAR(20), `"+domingo+"` VARCHAR(20), `"  +lunes+"` VARCHAR(20), `" +martes+"` VARCHAR(20), `" +miercoles+"` VARCHAR(20), `" +jueves+"` VARCHAR(20), `" +viernes+"` VARCHAR(20), " + "Horas VARCHAR(20))";
            PreparedStatement pst = cn.prepareStatement(sentencia);
            pst.executeUpdate();
            System.out.println("-Creada tabla (reporte"+actual+") - Ok");
            String mensaje = "-Creada tabla (reporte"+actual+") - Ok";
            notas (mensaje);
        }
        catch (Exception tabla) {
            System.out.println("Error al crear tabla "+ tabla);
            String mensaje = "Error al crear tabla "+ tabla;
            notas (mensaje);
        }
    }
    
    void LLenarTabla () {
        try {
            Calendar calendar =Calendar.getInstance(); //obtiene la fecha de hoy 
            String actual = (String.format("reporte%1$td-%1$tm-%1$ty",  calendar.getTime()));
            ConexionSQL con = new ConexionSQL();
            Connection cn = con.Conectar();
            String sentencia="SELECT*FROM reporte";
            PreparedStatement pst = cn.prepareStatement(sentencia);
            pst.executeUpdate();
        }
        catch (Exception llenado) {
            System.out.println("Error al llenar tabla "+llenado);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Migrar = new javax.swing.JButton();
        ELAVORAR = new javax.swing.JButton();
        ISERT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Migrar.setText("MIGRAR");
        Migrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MigrarActionPerformed(evt);
            }
        });

        ELAVORAR.setText("ELAVORAR");
        ELAVORAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELAVORARActionPerformed(evt);
            }
        });

        ISERT.setText("GENERAR TABLA");
        ISERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISERTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Migrar)
                    .addComponent(ELAVORAR)
                    .addComponent(ISERT))
                .addContainerGap(649, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Migrar)
                .addGap(53, 53, 53)
                .addComponent(ELAVORAR)
                .addGap(18, 18, 18)
                .addComponent(ISERT)
                .addContainerGap(362, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MigrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MigrarActionPerformed
        MigraraSQL es = new MigraraSQL();
        es.Migracion();
        CrearTabla();
    }//GEN-LAST:event_MigrarActionPerformed

    private void ELAVORARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELAVORARActionPerformed
        CrearTabla ();
    }//GEN-LAST:event_ELAVORARActionPerformed

    private void ISERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISERTActionPerformed
        LLenarTabla();
    }//GEN-LAST:event_ISERTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ELAVORAR;
    private javax.swing.JButton ISERT;
    private javax.swing.JButton Migrar;
    // End of variables declaration//GEN-END:variables
}
